server:
  port: 8080

spring:
  datasource:
    username: root
    password: 17635HJSFGDJhjasd1785634
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
      ddl-auto: update
    show-sql: false
indexing-settings:
  sites:
    - url: https://shop.mts.ru
      name: Mts.Ru
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://lenta.ru
      name: Lenta.Ru

